<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PrimeOps.ENTITY\PrimeOps.ENTITY.csproj" />
    <ProjectReference Include="..\PrimeOps.LOGGER\PrimeOps.LOGGER.csproj" />
    <ProjectReference Include="..\PrimeOps.PYTHON\PrimeOps.PYTHON.csproj" />
  </ItemGroup>

</Project>
